api_keys:
  qwen:
    api_key: sk-
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  deepseek:
    api_key: sk-
    base_url: https://api.deepseek.com
  ernie:
    api_key: bce-v3/ALTAK-/
    base_url: https://qianfan.baidubce.com/v2
  ark:
    api_key: cfv
    base_url: https://ark.cn-beijing.volces.com/api/v3
  gaode:
    api_key: fv
  
  openweather:
    api_key: fdfef30337b4dea4
  send_url:
    url: http://120.77.8.73/sale/wechat/message/send