api_keys:
  qwen:
    api_key: sk-ad30851f6a47453a8b2c56ec4da32957
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  deepseek:
    api_key: sk-d0dcd1cb9600485d951f604146e3f1ea
    base_url: https://api.deepseek.com
  ernie:
    api_key: bce-v3/ALTAK-wKuFEIj8EXZqIDOquAnsT/678c3407baba1a9b64ab889a7f7becd7dc3a4591
    base_url: https://qianfan.baidubce.com/v2
  gaode:
    api_key: af8a9fd3dac89fe58d1ab4a2fa142a30
  
  openweather:
    api_key: fdfaba4dcbf1ddb354b4b30337b4dea4
