database:
  # SQLite配置
  driver: 'sqlite'
  database_path: 'database/sale.db'
  # 连接池配置（SQLite不需要复杂的连接池）
  pool_size: 1
  max_overflow: 0
  pool_recycle: 3600
  pool_pre_ping: true
  pool_timeout: 30
  connect_timeout: 10 